### ISSUE TITLE
_expected.pkl is not found

### ISSUE THREAD

**Issue by Bo-UT** [XiaoTaoWang/EagleC#10]
Hi Xiaotao, 

Thanks for all your help! Sorry to bother you again, but I got another error saying ".231043-HC01_5000.mcool.175822081.CNV.None.100000.None/chr4_expected.pkl". I listed the directory .231043-HC01_5000.mcool.175822081.CNV.None.100000.None, but I do see 'chr4_expected.pkl' is there. 
Not sure what's the problem there. 
Thanks.

Bo

FileNotFoundError: [Errno 2] No such file or directory: '.231043-HC01_5000.mcool.175822081.CNV.None.100000.None/chr4_expected.pkl'
Traceback (most recent call last):
  File "/rsrch4/home/genomic_med/bzhao2/miniconda3/envs/EagleC/bin/predictSV", line 176, in <module>
    run()
  File "/rsrch4/home/genomic_med/bzhao2/miniconda3/envs/EagleC/bin/predictSV", line 159, in run
    subprocess.check_call(' '.join(command), shell=True)
  File "/rsrch4/home/genomic_med/bzhao2/miniconda3/envs/EagleC/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'merge-multiple-resolutions --hic-10k ../CatalystHiCmcool/231045-HC01_5000.mcool::resolutions/10000 --hic-5k ../CatalystHiCmcool/231045-HC01_5000.mcool::resolutions/5000 --balance-type CNV -C "#" "X" --full-sv-files 231045-HC01_5000.CNN_SVs.5K.txt 231045-HC01_5000.CNN_SVs.10K_highres.txt 231045-HC01_5000.CNN_SVs.50K_highres.txt -O 231045-HC01_5000.CNN_SVs.5K_combined.txt --buff-size 50000 --output-format NeoLoopFinder --cache-10k .231043-HC01_5000.mcool.175822081.CNV.None.100000.None --cache-5k .235206-HC01_5000.mcool.131736076.CNV.None.100000.None' returned non-zero exit status 1.

**Comment by XiaoTaoWang** [comment]
Hi Bo,

I think this error was caused by a bug in ``predictSV``, because ``predictSV`` extracts the ``--cache-10k`` and ``--cache-5k`` from your log file, and if you ran ``predictSV`` with the same ``--logFile`` setting on multiple samples, this function can result in conflicts. That's why in your log, the prefixes of ``--cache-10k`` and ``--cache-5k`` are different from your cool files.

I have fixed this by removing the ``--logFile`` parameter in the new version (v0.1.7), and now the log file name will use the prefix determined by ``--output-prefix`` as well. Can you try this new version and let me know if it works (you may need to rerun EagleC in a fresh new folder)? Thanks!

Xiaotao

**Comment by Bo-UT** [comment]
sure thing! Will let you know how it works.
Thanks

Bo

**Comment by Bo-UT** [comment]
Hi Xiaotao, 

Wanted to let you know that V0.1.7 EagleC works. So far one third of my jobs have been successfully done. 
Thanks a lot for your help!


Best, 
Bo

**Comment by XiaoTaoWang** [comment]
Great! Thanks for letting me know.

Xiaotao
